export const ENABLE_MODULE = "ENABLE_MODULE";
export const CHANGE_TOTAL = "CHANGE_TOTAL";
export const CHANGE_MAXIMUM_SUM = "CHANGE_MAXIMUM_SUM";
export const CHANGE_MAXIMUM_MINUEND = "CHANGE_MAXIMUM_MINUEND";
export const CHANGE_MAXIMUM_MULTIPLIER = "CHANGE_MAXIMUM_MULTIPLIER";
export const CHANGE_MAXIMUM_DIVIDENT = "CHANGE_MAXIMUM_DIVIDENT";
